# Generated by Django 2.2 on 2021-04-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
