# Generated by Django 2.2 on 2021-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='home_page')),
                ('main_image_alt', models.CharField(max_length=250)),
                ('main_image_alt_de', models.CharField(max_length=250, null=True)),
                ('main_image_alt_en', models.CharField(max_length=250, null=True)),
                ('header', models.CharField(max_length=250)),
                ('header_de', models.CharField(max_length=250, null=True)),
                ('header_en', models.CharField(max_length=250, null=True)),
                ('logo', models.ImageField(upload_to='home_page')),
                ('about_us', models.TextField()),
                ('about_us_de', models.TextField(null=True)),
                ('about_us_en', models.TextField(null=True)),
                ('card_one', models.CharField(max_length=250)),
                ('card_one_de', models.CharField(max_length=250, null=True)),
                ('card_one_en', models.CharField(max_length=250, null=True)),
                ('card_one_description', models.TextField()),
                ('card_one_description_de', models.TextField(null=True)),
                ('card_one_description_en', models.TextField(null=True)),
                ('card_one_image', models.ImageField(upload_to='home_page')),
                ('card_two', models.CharField(max_length=250)),
                ('card_two_de', models.CharField(max_length=250, null=True)),
                ('card_two_en', models.CharField(max_length=250, null=True)),
                ('card_two_description', models.TextField()),
                ('card_two_description_de', models.TextField(null=True)),
                ('card_two_description_en', models.TextField(null=True)),
                ('card_two_image', models.ImageField(upload_to='home_page')),
                ('card_three', models.CharField(max_length=250)),
                ('card_three_de', models.CharField(max_length=250, null=True)),
                ('card_three_en', models.CharField(max_length=250, null=True)),
                ('card_three_description', models.TextField()),
                ('card_three_description_de', models.TextField(null=True)),
                ('card_three_description_en', models.TextField(null=True)),
                ('card_three_image', models.ImageField(upload_to='home_page')),
                ('preporyka1', models.CharField(max_length=250)),
                ('preporyka1_de', models.CharField(max_length=250, null=True)),
                ('preporyka1_en', models.CharField(max_length=250, null=True)),
                ('preporyka2', models.CharField(max_length=250)),
                ('preporyka2_de', models.CharField(max_length=250, null=True)),
                ('preporyka2_en', models.CharField(max_length=250, null=True)),
                ('preporyka3', models.CharField(max_length=250)),
                ('preporyka3_de', models.CharField(max_length=250, null=True)),
                ('preporyka3_en', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
